# Generated by Django 5.2.15 on 2026-06-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_steamprofile_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamprofile',
            name='faceit_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='steamprofile',
            name='faceit_vip_granted',
            field=models.BooleanField(default=False),
        ),
    ]
