# Generated by Django 5.2.15 on 2026-06-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_steamprofile_faceit_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id', models.CharField(max_length=64, unique=True)),
                ('data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='skins_archived',
            field=models.BooleanField(default=False),
        ),
    ]
