# Generated by Django 4.2.30 on 2026-06-08 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField(default=27015)),
                ('rcon_password', models.CharField(max_length=128)),
                ('region', models.CharField(default='uz', max_length=50)),
                ('is_online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('workshop_id', models.CharField(blank=True, max_length=64, null=True)),
                ('map_type', models.CharField(choices=[('vanilla', 'Vanilla'), ('bhop', 'Bhop'), ('surf', 'Surf'), ('retake', 'Retake'), ('dm', 'Deathmatch')], default='vanilla', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_current', models.BooleanField(default=False)),
                ('position_in_cycle', models.IntegerField(default=0)),
                ('play_count', models.IntegerField(default=0)),
                ('avg_completion_time', models.FloatField(default=0.0)),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('download_url', models.URLField(blank=True)),
                ('gravity', models.FloatField(default=1.0)),
                ('max_velocity', models.IntegerField(default=3500)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='servers.gameserver')),
            ],
        ),
        migrations.CreateModel(
            name='ServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamemode', models.CharField(choices=[('bhop', 'Bhop'), ('surf', 'Surf'), ('dm', 'Deathmatch'), ('kz', 'KZ'), ('aim', 'Aim')], default='bhop', max_length=20)),
                ('max_players', models.IntegerField(default=24)),
                ('tickrate', models.IntegerField(default=128)),
                ('timer_enabled', models.BooleanField(default=True)),
                ('bhop_enabled', models.BooleanField(default=True)),
                ('map_cycle_enabled', models.BooleanField(default=True)),
                ('current_map', models.CharField(blank=True, max_length=64)),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='servers.gameserver')),
            ],
        ),
        migrations.CreateModel(
            name='MapConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gravity', models.FloatField(default=1.0)),
                ('max_velocity', models.IntegerField(default=3500)),
                ('air_accelerate', models.FloatField(default=800)),
                ('bhop_enabled', models.BooleanField(default=True)),
                ('auto_bhop', models.BooleanField(default=False)),
                ('server_map', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='servers.servermap')),
            ],
        ),
    ]
