# Generated by Django 5.2.15 on 2026-06-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermap',
            name='bonus_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servermap',
            name='stages',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='servermap',
            name='tier',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servermap',
            name='map_type',
            field=models.CharField(choices=[('vanilla', 'Vanilla'), ('bhop', 'Bhop'), ('surf', 'Surf'), ('kz', 'KZ'), ('aim', 'Aim'), ('retake', 'Retake'), ('dm', 'Deathmatch')], default='vanilla', max_length=20),
        ),
    ]
