# Generated by Django 5.2.15 on 2026-06-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_servermap_bonus_count_servermap_stages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameserver',
            name='bat_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
