# Generated by Django 5.2.15 on 2026-06-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_gameserver_bat_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameserver',
            name='current_map',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='gameserver',
            name='map_image',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
