# Generated by Django 5.2.15 on 2026-06-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_gameserver_current_map_gameserver_map_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameserver',
            name='server_type',
            field=models.CharField(choices=[('surf', 'Surf'), ('bhop', 'Bhop'), ('kz', 'KZ'), ('1v1', '1v1'), ('aim', 'Aim'), ('dm', 'DM'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
