# Generated by Django 5.2.15 on 2026-06-09 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=10)),
                ('time_ms', models.FloatField()),
                ('jumps', models.IntegerField(default=0)),
                ('set_at', models.DateTimeField()),
                ('improvement_ms', models.FloatField(default=0.0)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_history', to='servers.servermap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-set_at'],
            },
        ),
        migrations.CreateModel(
            name='MapCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(default='normal', max_length=10)),
                ('count', models.IntegerField(default=1)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='servers.servermap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'map', 'style')},
            },
        ),
        migrations.CreateModel(
            name='PlayerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('normal', 'Normal'), ('sw', 'Sideways'), ('hsw', 'Half-Sideways'), ('wr', 'WR Style'), ('auto', 'Auto-bhop')], default='normal', max_length=10)),
                ('time_ms', models.FloatField()),
                ('jumps', models.IntegerField(default=0)),
                ('strafes', models.IntegerField(default=0)),
                ('sync', models.FloatField(default=0.0)),
                ('pre_speed', models.FloatField(default=0.0)),
                ('max_speed', models.FloatField(default=0.0)),
                ('set_at', models.DateTimeField(auto_now_add=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='servers.servermap')),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='servers.gameserver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['time_ms'],
                'indexes': [models.Index(fields=['map', 'style', 'time_ms'], name='records_pla_map_id_1c374a_idx'), models.Index(fields=['user', 'map'], name='records_pla_user_id_9f3ee1_idx')],
                'unique_together': {('user', 'map', 'style')},
            },
        ),
    ]
