# Generated by Django 5.2.15 on 2026-06-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='STPlayerRecord',
            fields=[
                ('SteamID', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('MapName', models.CharField(max_length=128)),
                ('PlayerName', models.CharField(blank=True, max_length=128)),
                ('TimerTicks', models.IntegerField(default=0)),
                ('FormattedTime', models.CharField(max_length=32)),
                ('UnixStamp', models.IntegerField(default=0)),
                ('TimesFinished', models.IntegerField(default=0)),
                ('LastFinished', models.IntegerField(default=0)),
                ('Style', models.IntegerField(default=0)),
                ('Mode', models.TextField(default='Standard')),
            ],
            options={
                'db_table': 'PlayerRecords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='STPlayerStats',
            fields=[
                ('SteamID', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('PlayerName', models.CharField(blank=True, max_length=128)),
                ('GlobalPoints', models.IntegerField(default=0)),
                ('TimesConnected', models.IntegerField(default=0)),
                ('LastConnected', models.IntegerField(default=0)),
                ('HideStats', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'PlayerStats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CheckpointStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id', models.CharField(max_length=64)),
                ('map_name', models.CharField(max_length=128)),
                ('style', models.IntegerField(default=0)),
                ('cp_count', models.IntegerField(default=0)),
                ('tp_count', models.IntegerField(default=0)),
                ('time_ms', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['map_name', 'style'], name='records_che_map_nam_a04234_idx')],
                'unique_together': {('steam_id', 'map_name', 'style')},
            },
        ),
    ]
